[package]
name = "rnes"
version = "0.1.0"
authors = ["Nikita Pekin <contact@nikitapek.in>"]

[lib]
name = "rnes"
path = "src/lib.rs"

[[bin]]
name = "rnes"
path = "src/main.rs"

[dependencies]
clippy = { version = "0.0", optional = true }
nom = "3.2.1"
